version: '3.1'
services:
  mysql:
    image: 'mariadb:10.3'
    container_name: mysql
    working_dir: /var/www/project
    volumes:
        - ../mysql:/var/lib/mysql
        - ../mysql-files:/var/lib/mysql-files
        - ../project:/var/www/project
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    working_dir: /var/www/project
    volumes:
        - ../project:/var/www/project
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
    links:
     - php-fpm

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    working_dir: /var/www/project
    volumes:
      - ../project:/var/www/project
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    links:
      - mailhog
      - mysql

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog
    ports:
      - "8125:8025"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:     
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      # Persist data
      - './redis-persistence/redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local